variables:
  service_name: covid-19-test-result
  short_service_name: c19tr
  service_base_path: covid-19-test-result
  product_display_name: COVID-19 Test Result API
  product_description: This API will return a list of antibody and antigen (PCR and LFT) COVID-19 test results for a given citizen based on NHS number and optionally verified by additional demographic data.
  spec_file: covid-19-test-result.json