openapi: 3.0.0
x-nhs-api-spec-guid: "bb24463f-9f34-4c78-9f49-088cb3b9d7b4"
tags:
  - name: Observation
info:
  version: 1.0.0
  title: COVID 19 Test Results FHIR API
  license:
    name: MIT
  contact:
    name: NHS Digital API Management
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  description: | 
    ## Overview
    Use this API to access a patient’s COVID-19 test results history.

    You can:
    - get a patient's coronavirus (COVID-19) tests history, based on their NHS number with a optional specific date range

    You cannot currently use this API to:
    - get details of other types of tests
    - get the tests history for a specific date range without NHS number
    
    You get the following data:
    - Covid test event details
    - Patient demographic details, as captured at the point of testing (next iteration)

    The patient demographic details might differ from those held in the [Personal Demographics Service (PDS)](https://digital.nhs.uk/services/demographics).
    To get demographic details from PDS, use the [Personal Demographics Service FHIR API](https://digital.nhs.uk/developer/api-catalogue/personal-demographics-service-fhir).
    
    ### Data availability, timing and quality
    All test records are verified to ensure the NHS number is correct before making them available via the API.
    
    In most cases this is automatic, and the record is available within 48 hours of the test event, sometimes sooner.
        
    In a very small number of cases, we are unable to verify the NHS number, and we do not make the test record available at all.

    ## Who can use this API
    This API:
    - is only for use by patient/citizen-facing applications
    - is only for non-clinical use
    - can only be used where there is a legal basis to do so
    
    Make sure you have a valid use case before you go too far with your development.
    To do this, [contact us](https://digital.nhs.uk/developer/help-and-support).
    You must do this before you can go live (see ‘Onboarding’ below).
    
    ## API status and roadmap    
    
    ### Status
    This API is in alpha, meaning:
    - it is available for testing but not yet for production use
    - we might make breaking changes
    
    If you would like to be involved in our beta programme, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest).
    It also conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir) global standard for health care data exchange.
    Specifically, it is aligned with [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), which is built on FHIR Release 4.
    You don’t need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, and use US spellings, for example `/Observation` not `/observation`
    - array names are singular, for example `entry` not `entries` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object
    There are [libraries and SDKs available](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) to help with FHIR API integration.
    
    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).
    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).
    
    ## Security and authorisation
    This API is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis),
    meaning we authenticate the calling application but not the end user.
    
    Specifically, it uses the following security pattern:
    - [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)
    Note that:
    - the end user must be a citizen
    - the calling application must strongly authenticate the end user using NHS login
    - specifically, the end user must have their identity verified to 'high' (P9) level
    - the calling application must pass the user's NHS login identity token in the `NHSD-User-Identity` header when calling the API
    - the NHS number in the identity token must match the NHS number for which data is being requested
    
    ## Environments and testing
    | Environment       | Base URL                                                               |
    | ----------------- | ---------------------------------------------------------------------- |
    | Sandbox           | `https://internal-qa-sandbox.api.service.nhs.uk/covid-19-test-result/` |
    | Integration test  | `https://internal-qa.api.service.nhs.uk/covid-19-test-result/`         |
    | Production        | Not yet available                                                      |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is open access, so does not allow you to test authorisation
    For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
    * is for formal integration testing
    * includes authorisation
         
    Currently, the integration test environment isn't fully available.
    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).
    
    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.
    Details to follow.
servers:
  - url: 'https://internal-qa-sandbox.api.service.nhs.uk/covid-19-test-result'
    description: Internal Sandbox environment
  - url: 'https://internal-qa.api.service.nhs.uk/covid-19-test-result'
    description: Internal Integration environment
paths:
  /observation:
    get:
      summary: Get COVID19 tests history for a given patient
      operationId: get-covid-test-history
      tags:
        - Observation
      description: |
        Given an NHS number, get the patient's Covid19 tests history.
        Also returns the patient's demographic details, as captured at the point of testing.
        
        ## Sandbox testing
        You can test the following scenarios in our sandbox environment:
        
        | Scenario                      | Request                                                              | Response                                   |
        | ----------------------------- | -------------------------------------------------------------------- | ------------------------------------------ |
        | Covid19 tests history found   | `patient.identifier`=`https://fhir.nhs.uk/Id/nhs-number\|1234567890` | HTTP Status 200 with test results data in response body |
        | No test results found         | `patient.identifier`= anything else                                  | HTTP Status 200 with empty bundle in response body |
        You can try out the sandbox using the 'Try this API' feature on this page.
      parameters:
        - in: header
          name: Authorization
          description: |
            An OAuth 2.0 bearer token, obtained using our [signed JWT authentication pattern](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication).
          required: true
          schema:
            type: "string"
            format: "^Bearer\\ [[:ascii:]]+$"
            example: "Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM"
        - in: header
          name: "X-Request-ID"
          required: false
          description: "A globally unique identifier (GUID) for the request"
          schema:
            type: "string"
            pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
            example: "60E0B220-8136-4CA5-AE46-1D97EF59D068"
        - name: NHSD-User-Identity
          in: header
          description: |
            NOT IMPLEMENTED YET
            Open ID Connect ID token for the end user citizen, as obtained from NHS login.
            Must be a signed JWT in the format `xxxxx.yyyyy.zzzzz`.
            Must be valid i.e. not expired.
            Must be for a user who has had their identity verified to 'high' (P9) level.
          required: false
          schema:
            type: string
            example: xxxxx.yyyyy.zzzzz
        - name: NHSD-Client-RP-Details
          in: header
          description: |
            NOT IMPLEMENTED YET
            Client details as registered with API Management platform
          required: false
          schema:
            type: string
        - in: header
          name: X-Correlation-ID
          required: false
          description: |
            An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.
            
            Mirrored back in a response header.
          schema:
            type: string
            example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
        - in: query
          name: patient.identifier
          description: |
            The patient's NHS number.
            Expressed as `<type>|<value>` where `<type>` must be `https://fhir.nhs.uk/Id/nhs-number` and `<value>` must be a [valid NHS number](https://www.datadictionary.nhs.uk/data_dictionary/attributes/n/nhs/nhs_number_de.asp).
          required: true
          schema:
            type: string
            example: "https://fhir.nhs.uk/Id/nhs-number|1234567890"
        - in: query
          name: date
          description: the effective date range as to when the observation was recorded and can be used multiple times as a search parameter
          required: false
          schema:
            type: string
            example:  "ge2010-01-01&date=le2011-12-31"
        - in: query
          name: code
          description: "The SNOMED code related to the observation type"
          required: false
          schema:
            type: string
            example: "871562009"
      responses:
        '200':
          description: Valid request that returns all accredited systems found that match the search criteria (which may be 0).
          headers:
            X-Correlation-Id:
              schema:
                type: string
                example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
              description: The X-Correlation-ID from the request header, if supplied, mirrored back.
          content:
            application/fhir+json:
              schema:
                $ref: '#/components/schemas/observationExample'
        '400':
          description: Missing or invalid query parameter(s).
        '401':
          description: Missing or invalid ID/OAuth toke or NHS number in request doesn't match NHS number in ID token
        '404':
          description: Invalid endpoint path
        '500':
          description: Any Server error
components:
  schemas:
    observationExample:
      type: object
      example:
        resourceType: Bundle
        id: 1a420b58-5b91-4706-9a7c-90028ca79ff3
        meta:
          lastUpdated: '2021-01-20T12:46:07.830+00:00'
        type: searchset
        total: 2
        entry:
        - fullUrl: https://test-results-api.nhs.uk/R4/Observation/eb89a392-5b20-11eb-ae93-0242ac130002
          resource:
            resourceType: Observation
            id: ASD32145123
            identifier:
            - system: https://fhir.nhs.uk/Id/SpecimenId
              value: ASD32145123
            status: final
            subject:
              reference: Patient/1234567890
              type: Patient
              identifier:
              - system: https://fhir.nhs.uk/Id/nhs-number
                value: '1234567890'
            code:
              coding:
              - system: http://snomed.info/sct
                code: '871562009'
                display: Detection of Severe acute respiratory syndrome coronavirus 2 (observable
                  entity)
            effectiveDateTime: '2020-09-23T13:00:08.476+00:00'
            valueCodeableConcept:
              coding:
              - system: http://snomed.info/sct
                code: '1240581000000104'
                display: SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) detection
                  result positive
              text: SARS-CoV-2-ORGY
            method:
              coding:
              - system: http://snomed.info/sct
                code: '1240471000000102'
                display: Measurement of Severe acute respiratory syndrome coronavirus 2 antigen
                  (observable entity)
            device:
              identifier:
              - system: https://fhir.nhs.uk/Id/Covid19-TestKit
                value: LFT
                display: Lateral Flow Test
            performer: {}
            extension: {}
          search:
            mode: match
        - fullUrl: https://test-results-api.nhs.uk/R4/Observation/05ac9ea0-5b21-11eb-ae93-0242ac130002
          resource:
            resourceType: Observation
            id: 05ac9ea0-5b21-11eb-ae93-0242ac130002
            identifier:
            - system: 'https://fhir.nhs.uk/Id/SpecimenId'
              value: ASD32145127
            status: final
            subject:
              reference: Patient/1234567890
              type: Patient
              identifier:
              - system: https://fhir.nhs.uk/Id/nhs-number
                value: '1234567890'
            code:
              coding:
              - system: http://snomed.info/sct
                code: '871562009'
                display: Detection of Severe acute respiratory syndrome coronavirus 2 (observable
                  entity)
            effectiveDateTime: '2020-09-23T13:00:08.476+00:00'
            valueCodeableConcept:
              coding:
              - system: http://snomed.info/sct
                code: '1240581000000104'
                display: SARS-CoV-2 (severe acute respiratory syndrome coronavirus 2) detection
                  result positive
              text: SARS-CoV-2-ORGY
            method:
              coding:
              - system: http://snomed.info/sct
                code: '1240471000000102'
                display: Measurement of Severe acute respiratory syndrome coronavirus 2 antigen
                  (observable entity)
            device:
              identifier:
              - system: https://fhir.nhs.uk/Id/Covid19-TestKit
                value: LFT
                display: Lateral Flow Test
            performer: {}
            extension: {}
          search:
            mode: match