openapi: 3.0.0
x-nhs-api-spec-guid: bb24463f-9f34-4c78-9f49-088cb3b9d7b4

info:
  version: v1.0.82-alpha
  title: COVID-19 Test History API
  license:
    name: MIT
  contact:
    name: NHS Digital API Management
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
  description: |
  
    <div class="nhsd-m-emphasis-box nhsd-m-emphasis-box--emphasis nhsd-!t-margin-bottom-6" aria-label="Highlighted Information">
        <div class="nhsd-a-box nhsd-a-box--border-blue">
            <div class="nhsd-m-emphasis-box__image-box">
                <figure class="nhsd-a-image">
                    <picture class="nhsd-a-image__picture">
                        <img src="//nhs-prod.global.ssl.fastly.net/svg-magic/binaries/content/gallery/icons/info.svg?colour=231f20" alt="" style="object-fit:fill">
                    </picture>
                </figure>
            </div>
            <div class="nhsd-m-emphasis-box__content-box">
                <div data-uipath="website.contentblock.emphasis.content" class="nhsd-t-word-break"><p class="nhsd-t-body">This API is in <a href="https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status">private beta</a>. If you want to be involved, <a href="https://digital.nhs.uk/developer/help-and-support">contact us</a>.</p></div>            
            </div>
        </div>
    </div>

    ## Overview
    Use this API to access a patient’s coronavirus (COVID-19) test results history.

    You can:
    - get a patient's COVID-19 test history, based on their NHS number with an optional specific date range

    You cannot currently use this API to:
    - get details of other types of test

    You get the following data:
    - COVID-19 test event details

    ### Data availability, timing and quality
    All test records are verified to ensure the NHS number is correct before making them available via the API.

    In most cases this is automatic, and the record is available within 48 hours of the test event, sometimes sooner.
        
    In a very small number of cases, we are unable to verify the NHS number, and we do not make the test record available at all.

    ## Who can use this API
    This API:
    - is only for use by patient-facing applications
    - is only for non-clinical use
    - can only be used where there is a legal basis to do so

    Make sure you have a valid use case before you go too far with your development.
    To do this, [contact us](https://digital.nhs.uk/developer/help-and-support).
    
    You must do this before you can go live (see ‘Onboarding’ below).

    ## API status and roadmap    

    ### Status
    This API is in [private beta](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status), meaning:
    - it is available for testing use
    - it is available for production use after approval and adding to private beta
    - we might make breaking changes

    #### Roadmap
    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?order=popular&filter=allexceptdone&tag=covid-test-results-api#controls).

    If you would like to be involved in our beta programme or have any other queries, [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Service level
    This API is a platinum service, meaning it is operational and supported 24 x 7 x 365.
    
    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).
    
    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    It conforms to the [FHIR](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#fhir) global standard for health care data exchange, specifically to [FHIR R4 (v4.0.1)](https://hl7.org/fhir/r4/), except that it does not support the [capabilities](http://hl7.org/fhir/R4/http.html#capabilities) interaction.

    It includes some country-specific FHIR extensions, which conform to [FHIR UK Core](https://digital.nhs.uk/services/fhir-uk-core), specifically [fhir.r4.ukcore.stu1 0.5.1](https://simplifier.net/packages/fhir.r4.ukcore.stu1/0.5.1).
    
    You do not need to know much about FHIR to use this API - FHIR APIs are just RESTful APIs that follow specific rules.
    In particular:
    - resource names are capitalised and singular, and use US spellings, for example `/Observation` not `/observation`
    - array names are singular, for example `entry` not `entries` for address lines
    - data items that are country-specific and thus not included in the FHIR global base resources are usually wrapped in an `extension` object
    
    There are [libraries and SDKs available](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#fhir-libraries-and-sdks) to help with FHIR API integration.

    ## Network access
    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).
    
    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    
    This API has two access modes: 
    * application-restricted access
    * user-restricted access
    
    ### Application-restricted access
    
    This access mode is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate the calling application but not the end user.
    
    To use this access mode, use the following security pattern:
    * [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)
    
    ### User-restricted access
    Use this [user-restricted access mode](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#user-restricted-apis) if the end user is a patient:
    * the end user must have their identity verified to 'high' (P9) level
    * the NHS number in the request must match the NHS number in the NHS login account
    
    To use this access mode, use the following security pattern:
    * [User-restricted RESTful APIs - NHS login separate authentication and authorisation](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/user-restricted-restful-apis-nhs-login-separate-authentication-and-authorisation)

   
    ## Environments and testing
    | Environment       | Base URL                                                               | Associated NHS login environment |
    | ----------------- | ---------------------------------------------------------------------- | -----------------------------    |
    | Sandbox           | `https://sandbox.api.service.nhs.uk/covid-19-test-result/FHIR/R4`      | None                             |
    | Development       | `https://dev.api.service.nhs.uk/covid-19-test-result/FHIR/R4`          | NHS login - Sandpit              |
    | Integration       | `https://int.api.service.nhs.uk/covid-19-test-result/FHIR/R4`          | NHS login - Integration (aos)    |
    | Production        | `https://api.service.nhs.uk/covid-19-test-result/FHIR/R4`              | NHS login - Live (production)    |

    ### Sandbox testing
    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):
    * is for early developer testing
    * only covers a limited set of scenarios
    * is open access, so does not allow you to test authorisation
    
    For details of sandbox test scenarios, or to try out the sandbox using our 'Try this API' feature, see the documentation for each endpoint.

    Alternatively, you can try out the sandbox using our Postman collection:
    
    [![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/98198e55d31dd66b9c76)

    ### Development testing
    Our development  environment:
    * is for early development testing
    * includes authorisation using the NHS Sandpit

    Available test NHS patients:

    | NHS number        |
    | ----------------- |
    | 9686368973        |
    | 9686368906        |
    | 9658218873        |
    | 9658218881        |

    ### Integration testing
    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):
    * is for formal integration testing
    * includes authorisation
         
    Available test NHS patients:
    
    | NHS number        | Data profile |
    | ----------------- | ------------ | 
    | 9658477860        | profile 2    |
    | 9437573999        | profile 5    |
    | 9453634980        | profile 6    |
    
    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).

    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.
    
    For further information on onboarding contact [api.management@nhs.net](mailto:api.management@nhs.net).
servers:
  - url: 'https://sandbox.api.service.nhs.uk/covid-19-test-result/FHIR/R4'
    description: Sandbox environment
  - url: 'https://dev.api.service.nhs.uk/covid-19-test-result/FHIR/R4'
    description: Development environment
  - url: 'https://int.api.service.nhs.uk/covid-19-test-result/FHIR/R4'
    description: Integration environment
paths:
  /Observation:
    get:
      summary: Get COVID-19 test history
      
      operationId: get-covid-test-history
      description: |
        Given an NHS number, get the patient's COVID-19 test history.

        ## Sandbox testing
        You can test the following scenarios in our sandbox environment:

        | Scenario                      | Request                                                              | Response                                   |
        | ----------------------------- | -------------------------------------------------------------------- | ------------------------------------------ |
        | COVID-19 test history found   | `patient.identifier`=`https://fhir.nhs.uk/Id/nhs-number\|9000000009` | HTTP Status 200 with test results data in response body |
        | No test results found         | `patient.identifier`=`https://fhir.nhs.uk/Id/nhs-number\|9000000033` | HTTP Status 200 with empty bundle in response body |
        | Bad Request                   | `patient.identifier`= anything else                                  | HTTP Status 400 Bad Request |

        You can try out the sandbox using the 'Try this API' feature on this page.
      parameters:
        - in: header
          name: Authorization
          description: |
            An OAuth 2.0 bearer token, obtained using our [signed JWT authentication pattern](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication).
          required: true
          schema:
            type: string
            format: '^Bearer\ [[:ascii:]]+$'
            example: Bearer g1112R_ccQ1Ebbb4gtHBP1aaaNM
        - name: NHSD-User-Identity
          in: header
          description: |
            Open ID Connect ID token for the end user patient, as obtained from NHS login.
            Must be a signed JWT in the format `xxxxx.yyyyy.zzzzz`.
            Must be valid i.e. not expired.
            Must be for a user who has had their identity verified to 'high' (P9) level.
          required: true
          schema:
            type: string
            example: xxxxx.yyyyy.zzzzz
        - in: header
          name: X-Correlation-ID
          required: false
          description: |
            An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.

            Mirrored back in a response header.
          schema:
            type: string
            example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
        - in: query
          name: patient.identifier
          description: |
            The patient's NHS number.
            Expressed as `<type>|<value>` where `<type>` must be `https://fhir.nhs.uk/Id/nhs-number` and `<value>` must be a [valid NHS number](https://www.datadictionary.nhs.uk/attributes/nhs_number.html).
          required: true
          schema:
            type: string
            example: 'https://fhir.nhs.uk/Id/nhs-number|9000000009'
        - in: query
          name: date
          description: The effective date range when the observation was recorded and can be used multiple times as a search parameter.
          required: false
          schema:
            type: string
            example: ge2010-01-01&date=le2011-12-31
        - in: query
          name: code
          description: The SNOMED code related to the observation type. It supports a single value or comma separated values (for example 871555000,871553007) [List of available codes](https://simplifier.net/guide/NHSDigital/Home/FHIRAssets/AllAssets/ObservationDefinition?version=current)
          required: false
          schema:
            type: string
            example: '871553007'
        - in: query
          name: _include
          description: Adds Patient resource to the search response.
          required: false
          schema:
            type: string
            example: 'Observation:patient'
      responses:
        '200':
          description: Valid request that returns test results history found that match the search criteria (which may be 0).
          headers:
            X-Correlation-Id:
              schema:
                type: string
                example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
              description: 'The X-Correlation-ID from the request header, if supplied, mirrored back.'
          content:
            application/fhir+json:
              schema:
                $ref: "components/schemas/observation-bundle-schema.yaml"
              example:
                $ref: "components/examples/observation-bundle-example.json"

        '400':
          description: Missing or invalid query parameter(s).
        '401':
          description: Missing or invalid ID/OAuth toke or NHS number in request doesn't match NHS number in ID token.
        '404':
          description: Invalid endpoint path.
